/**
 * Icon library — all icons sourced from Lucide (https://lucide.dev)
 * Same export names as before so no imports need to change across the app.
 */
export {
    LayoutDashboard   as LayoutDashboardIcon,
    Map               as MapIcon,
    Users             as UsersIcon,
    Banknote          as BanknoteIcon,
    Plus              as PlusIcon,
    Car               as CarIcon,
    Sparkles          as SparklesIcon,
    Trash2            as TrashIcon,
    UserPlus          as UserPlusIcon,
    X                 as XIcon,
    Pencil            as EditIcon,
    Camera            as CameraIcon,
    Menu              as MenuIcon,
    Globe             as GlobeIcon,
    Lock              as LockIcon,
    CalendarDays      as CalendarIcon,
    Trophy            as TrophyIcon,
    Check             as CheckIcon,
    CheckCircle2      as CheckCircleIcon,
    LogOut            as LogOutIcon,
    SlidersHorizontal as FilterIcon,
    Download          as DownloadIcon,
    ChevronDown       as ChevronDownIcon,
    Siren             as SirenIcon,
    Award             as MedalIcon,
    TrendingUp        as TrendingUpIcon,
    TrendingDown      as TrendingDownIcon,
    Wallet            as WalletIcon,
    Sun               as SunIcon,
    Moon              as MoonIcon,
    ChevronLeft       as ChevronLeftIcon,
    ChevronRight      as ChevronRightIcon,
    Search            as SearchIcon,
    List              as ListIcon,
    LayoutGrid        as GridIcon,
    AlarmClock        as ClockAlertIcon,
    Calculator        as CalculatorIcon,
    AlertCircle       as AlertCircleIcon,
    CircleArrowLeft   as ArrowLeftCircleIcon,
    Eye               as EyeIcon,
    EyeOff            as EyeOffIcon,
    Phone             as PhoneIcon,
    User              as UserIcon,
    ShieldCheck       as ShieldIcon,
    FileText          as NotesIcon,
    // Extra icons — available for new use anywhere in the app
    Bell              as BellIcon,
    Send              as SendIcon,
    Clock             as ClockIcon,
    CircleCheck       as CircleCheckIcon,
    TriangleAlert     as WarningIcon,
    Info              as InfoIcon,
    RefreshCw         as RefreshIcon,
    ArrowUpRight      as ArrowUpRightIcon,
    ArrowDownRight    as ArrowDownRightIcon,
    Settings          as SettingsIcon,
    ChevronUp         as ChevronUpIcon,
    CreditCard        as CreditCardIcon,
    Receipt           as ReceiptIcon,
    Building2         as BuildingIcon,
    Star              as StarIcon,
    Zap               as ZapIcon,
    LogIn             as LogInIcon,
    UserCog           as UserCogIcon,
    MapPin            as MapPinIcon,
    Navigation        as NavigationIcon,
    Gauge             as GaugeIcon,
    Layers            as LayersIcon,
    MoreVertical      as MoreVerticalIcon,
    ExternalLink      as ExternalLinkIcon,
    PanelLeft         as SidebarIcon,
    ArrowLeft         as ArrowLeftIcon,
    ArrowRight        as ArrowRightIcon,
    Minus             as MinusIcon,
    Tag               as TagIcon,
    Hash              as HashIcon,
    Percent           as PercentIcon,
    Package           as PackageIcon,
    AlertTriangle     as AlertTriangleIcon,
    CheckSquare       as CheckSquareIcon,
    Copy              as CopyIcon,
    Share2            as ShareIcon,
    Printer           as PrinterIcon,
    FileDown          as FileDownIcon,
} from 'lucide-react';

// Telegram brand icon — not in Lucide, kept as custom SVG
import React from 'react';
export const TelegramIcon = ({ className }: { className?: string }) => (
    <svg className={className} viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path d="M12 0C5.373 0 0 5.373 0 12s5.373 12 12 12 12-5.373 12-12S18.627 0 12 0zm5.894 8.221-1.97 9.28c-.145.658-.537.818-1.084.508l-3-2.21-1.447 1.394c-.16.16-.295.295-.605.295l.213-3.053 5.56-5.023c.242-.213-.054-.333-.373-.12L8.32 13.617l-2.96-.924c-.643-.204-.657-.643.136-.953l11.57-4.461c.537-.194 1.006.131.828.942z"/>
    </svg>
);
